### ISSUE TITLE
Error with 2 specific plugin

### ISSUE THREAD

**Issue by bellanz80** [qgist/workbench#8] opened 2019-09-03 15:31 UTC
Hi, 
I am reviewing the new update 0.2
I have noticed the following:
- the problem with the "Load them all" plug has been completely solved.
- the error remains with the plug: "Bezier Editing" and "Azimut and Distance"

The error is as follows: the plug-in menu of the plug works, changing the profile changes the toolbar and panels, but, before the appearance of the GUI changes, the same previous error window opens, Once the button has been clicked , the error window disappears, and the plug still works.
![a](https://user-images.githubusercontent.com/38449926/64187284-faedfc80-ce35-11e9-83a5-ebb886423f30.jpg)
![b](https://user-images.githubusercontent.com/38449926/64187297-ffb2b080-ce35-11e9-9482-d632ae0ab28a.jpg)
![c](https://user-images.githubusercontent.com/38449926/64187306-03463780-ce36-11e9-8d7d-e1e7aa825839.jpg)

**Comment by s-m-e** [comment] 2019-09-03 17:27
Thanks for the report. Indeed, there is still a *warning* message. The message tells you that there are user interface elements without a name. I am considering to deactivate the message and instead write them to a log file. The root cause is in "Bezier Editing" and "Azimut and Distance" - they contain the unnamed user interface elements, just like many other plugins. It is technically almost impossible to properly track unnamed user interface elements. `workbench` can therefore not properly save their state or restore it. I do want to tell the user that something can not be tracked and saved. However, I also understand that those warning messages are annoying. I can add an option allowing you to turn the warnings on or off. How about that?

**Comment by bellanz80** [comment] 2019-09-03 17:36
I think it's a good idea.
Now I have a clear message, the plug is still working very well.
You could put a description in the documentation, and a message deactivation option

**Comment by bellanz80** [comment] 2019-09-04 14:46
Hi, is it possible change the name of the profile ?
Thank's!
![Anotación 2019-09-04 094627](https://user-images.githubusercontent.com/38449926/64265645-e9215d80-cef8-11e9-85ac-26743caadc29.jpg)

**Comment by os-geoinformatics** [comment] 2019-09-04 15:45
At the moment not. Its a missing feature and will be including in coming releases. See [issue 1](https://github.com/qgist/workbench/issues/1) where it will be documented.

**Comment by os-geoinformatics** [comment] 2019-09-04 15:46
@bellanz80 At the moment not. Its a missing feature and will be including in coming releases. See [issue 1](https://github.com/qgist/workbench/issues/1) where it will be documented.

**Comment by bellanz80** [comment] 2019-09-04 15:52
> @bellanz80 At the moment not. Its a missing feature and will be including in coming releases. See [issue 1](https://github.com/qgist/workbench/issues/1) where it will be documented.

Thank you!

**Comment by s-m-e** [comment] 2019-09-06 11:26
I implemented the option. By the default, the warnings are now turned off, so you should not see them anymore.

It will be part of the next release. I'll upload it probably sometimes later today.

**Comment by bellanz80** [comment] 2019-09-06 14:50
> I implemented the option. By the default, the warnings are now turned off, so you should not see them anymore.
> 
> It will be part of the next release. I'll upload it probably sometimes later today.

Thank's!!

**Closed as completed** 2019-09-08 17:08 UTC
Labels: enhancement

**Comment by s-m-e** [comment] 2019-09-08 18:42
@bellanz80 I released a new version which should fix all so far reported issues and includes import & export of workbenches, see [changes](https://github.com/qgist/workbench/blob/v0.0.3/CHANGES.md).

**Comment by bellanz80** [comment] 2019-09-09 00:08
really an important update! thank you! it will be a pleasure to use this plug in my computers!
