### ISSUE TITLE
Plug don't work

### ISSUE THREAD

**Issue by bellanz80** [qgist/workbench#4] opened 2019-09-02 16:28 UTC
Hi, I installed the plug without problems.
But, the top bar is disabled, I can't activate it.
Can you help me?
QGIS 3.8.2
Windows 10 64 bit v1903

Thank you very much

![Anotación 2019-09-02 112725](https://user-images.githubusercontent.com/38449926/64126781-be0e0100-cd74-11e9-8109-31e7bcc3b191.jpg)

**Comment by os-geoinformatics** [comment] 2019-09-02 16:36
Can you restart QGIS?. I think this is an issue with initial configurations and restarting should fix it.

**Comment by bellanz80** [comment] 2019-09-02 17:24
when restarting QGIS, now a new error comes out ... I have never seen it.
QGIS 3.8.2
QGIS 3.4.11
![Anotación 2019-09-02 110104](https://user-images.githubusercontent.com/38449926/64128548-a33f8a80-cd7c-11e9-8779-b0f75547ecb4.jpg)

I will perform a test with a clean profile, and update the post

**Comment by bellanz80** [comment] 2019-09-02 17:32
I tried a new, clean profile, and everything works correctly.
I suspect there is some incompatibility with some plugin.
I have installed many
In a moment of time, I will try to reinstall them one by one.
Meanwhile, congratulations on your plug. It's something I dreamed of in QGIS!

**Comment by s-m-e** [comment] 2019-09-02 17:32
@bellanz80 This plugin is working for you. The trouble is that it tries to identify all user interface elements of QGIS. Because some are unnamed, the identification sometimes fails. The root problem is somewhere in QGIS and the locale / translation that you're using, but I need to improve the handling of such events so you do not see this error message. What language / locale are you using? I'd like to reproduce the issue.

**Comment by s-m-e** [comment] 2019-09-02 17:35
@bellanz80 About the other issue, the disabled UI after installation, @os-geoinformatics is right. Currently, a restart of QGIS is required after installing this plugin. See #5. I will also fix that.

**Comment by os-geoinformatics** [comment] 2019-09-02 17:38
I tried on a clean installation of QGIS under windows and it works perfectly with US/EN locals.
![work_bench](https://user-images.githubusercontent.com/46866412/64128896-3f878280-cdb9-11e9-87b0-b84bbc33dc0b.PNG)

**Comment by bellanz80** [comment] 2019-09-02 17:43
QGIS is originally downloaded in Spanish, but I changed the language to American English.
You're right, the new profile was in Spanish, the original, and the plug worked.
But, with the profile I always use, full of plug, and returned to the Spanish language, it continues to give error.
Annex image, where the GUI is seen in Spanish, but with the same error
![Anotación 2019-09-02 124154](https://user-images.githubusercontent.com/38449926/64129028-295cd080-cd7f-11e9-8c48-d65e2b5da778.jpg)

I will continue testing with profile and languages.
Thank you very much

**Comment by bellanz80** [comment] 2019-09-02 17:49
I have tried the new, clean profile, both in Spanish and English, and it works perfectly.
It must be the fault of some plug that I have installed.
For the moment thank you very much for the availability

**Comment by s-m-e** [comment] 2019-09-02 17:49
@bellanz80 Ok, can you provide a list of plugins that you're currently using?

**Comment by bellanz80** [comment] 2019-09-02 17:52
Yes, but they are too many, I will install them one by one from a new profile, and see if I have problems
![Anotación 2019-09-02 125046](https://user-images.githubusercontent.com/38449926/64129210-78efcc00-cd80-11e9-8b69-31a598403008.jpg)

**Comment by bellanz80** [comment] 2019-09-02 18:14
In qgis new profile, I located the plug with error:
"Bezier Editing."
But, in the old profile, when removing that plug, another error comes out
![Anotación 2019-09-02 131319](https://user-images.githubusercontent.com/38449926/64129735-96726500-cd83-11e9-80c1-f298eb242513.jpg)

**Comment by s-m-e** [comment] 2019-09-02 18:19
@bellanz80 Just for clarification: You received this error message when you uninstalled/removed the plugin?

**Comment by os-geoinformatics** [comment] 2019-09-02 18:20
Thanks @bellanz80. @s-m-e look "Bezier Edition" is generating this error. Install it and you will get this error.

**Comment by s-m-e** [comment] 2019-09-02 18:24
@os-geoinformatics Thanks for the clarification, I see. I'll look into it.

**Comment by bellanz80** [comment] 2019-09-02 18:30
> @bellanz80 Just for clarification: You received this error message when you uninstalled/removed the plugin?

The error was when uninstalling it in the old profile, which I use daily and is full of plug.

**Comment by bellanz80** [comment] 2019-09-02 18:31
> Thanks @bellanz80. @s-m-e look "Bezier Edition" is generating this error. Install it and you will get this error.

There is another plug: Azimuth and Distance, but there must be others, I go one by one

**Comment by s-m-e** [comment] 2019-09-02 18:38
@bellanz80 Thanks for all the effort. I'll investigate them one by one and try to provide bug fixes for you.

**Comment by bellanz80** [comment] 2019-09-02 18:40
> @bellanz80 Thanks for all the effort. I'll investigate them one by one and try to provide bug fixes for you.

It is a pleasure to contribute, this plug I have waited for years!
I still install the plug one by one, for the moment everything is fine, in a hour I update the situation

**Comment by bellanz80** [comment] 2019-09-02 18:55
Other plug corrupt : "Load Them All"

**Comment by bellanz80** [comment] 2019-09-02 19:43
after uninstalling #Bezer "," Azimut -distance "and" load them all ", everything works perfectly, also in the old profile.
I have tried all the plug.

**Comment by bellanz80** [comment] 2019-09-03 03:41
I found another detail: on two different computers with windows 10, I created 2 new profiles in QGIS 3.8
The first add-on installed was Workbench, and then gradually installed other add-ons, to control possible errors.
But, I realized the following: the plug doesn't let me fit the panels in the same window.
It does not matter if I change the position of the panels, when restarting QGIS, always put the panels in the same way, unpinned.

image 1:
integrated panel layer to the browser panel
![a](https://user-images.githubusercontent.com/38449926/64142698-bc732600-cdd2-11e9-8fc0-ec74ac319b4b.jpg)

image 2: I close and open QGIS again, the panels are removed, and other panels are opened
![b](https://user-images.githubusercontent.com/38449926/64142704-c1d07080-cdd2-11e9-95f5-6304251bdaf2.jpg)

**Comment by s-m-e** [comment] 2019-09-03 10:11
Ok, I figured out why `workbench` crashed when you activate `load them all`. The fix is now in the `develop` branch, see #6.

**Comment by s-m-e** [comment] 2019-09-03 12:35
I also figured out why `Bezier Editing` would crash `workbench`, see #7. It is fixed in `develop`.

**Comment by s-m-e** [comment] 2019-09-03 12:41
`qgsazimuth` was also affected by #7. It should work now.

**Comment by s-m-e** [comment] 2019-09-03 12:45
> I found another detail: on two different computers with windows 10, I created 2 new profiles in QGIS 3.8
The first add-on installed was Workbench, and then gradually installed other add-ons, to control possible errors.
But, I realized the following: the plug doesn't let me fit the panels in the same window.
It does not matter if I change the position of the panels, when restarting QGIS, always put the panels in the same way, unpinned.

Once you have fitted the panels, you need to *save* the workbench, otherwise it does not memorize the last state. Do you still have this issue after saving the workbench? (Just use the *save* button in the `workbench` corner widget.)

**Comment by bellanz80** [comment] 2019-09-03 14:31
> > I found another detail: on two different computers with windows 10, I created 2 new profiles in QGIS 3.8
> > The first add-on installed was Workbench, and then gradually installed other add-ons, to control possible errors.
> > But, I realized the following: the plug doesn't let me fit the panels in the same window.
> > It does not matter if I change the position of the panels, when restarting QGIS, always put the panels in the same way, unpinned.
> 
> Once you have fitted the panels, you need to _save_ the workbench, otherwise it does not memorize the last state. Do you still have this issue after saving the workbench? (Just use the _save_ button in the `workbench` corner widget.)

Yes, it works perfect, it was my mistake not to save. An apology!

**Comment by bellanz80** [comment] 2019-09-03 14:32
> I also figured out why `Bezier Editing` would crash `workbench`, see #7. It is fixed in `develop`.

One question: develop refers to a new version of the plug, which will be published later, or a new version of QGIS?

**Comment by s-m-e** [comment] 2019-09-03 14:38
> One question: develop refers to a new version of the plug, which will be published later, or a new version of QGIS?

[`develop`](https://github.com/qgist/workbench/tree/develop) refers to a [git branch](https://git-scm.com/book/en/v2/Git-Branching-Branches-in-a-Nutshell), that will become a new (future) version of this plugin. You can theoretically [download it](https://github.com/qgist/workbench/archive/develop.zip) and test it right away.

**Comment by bellanz80** [comment] 2019-09-03 14:45
> > One question: develop refers to a new version of the plug, which will be published later, or a new version of QGIS?
> 
> [`develop`](https://github.com/qgist/workbench/tree/develop) refers to a [git branch](https://git-scm.com/book/en/v2/Git-Branching-Branches-in-a-Nutshell), that will become a new (future) version of this plugin. You can theoretically [download it](https://github.com/qgist/workbench/archive/develop.zip) and test it right away.

Ok, thenk you. I download develop and try

**Comment by s-m-e** [comment] 2019-09-03 14:58
@bellanz80 I just published a new official version. You can download / update it through QGIS. Can I close this GitHub issue? I believe I fixed every problem you found. Feel free to open new issues if you find any - I really appreciate your feedback!

**Comment by bellanz80** [comment] 2019-09-03 15:00
> @bellanz80 I just published a new official version. You can download / update it through QGIS. Can I close this GitHub issue? I believe I fixed every problem you found. Feel free to open new issues if you find any - I really appreciate your feedback!

Of course, and thank you very much.
I will look forward to the new version. When will it be available in the QGIS repository?

**Comment by s-m-e** [comment] 2019-09-03 15:05
As far as I can tell, it already [is available](https://plugins.qgis.org/plugins/workbench/version/0.0.2/).

**Closed as completed** 2019-09-08 11:50 UTC
